/*
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (c) 2025 Jesse Kane
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from this
 * software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS”
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

// This file was automatically generated by WIPS. Do not attempt to modify manually

#ifdef WIPS_OPTION_BUILD_PYTHON

#ifdef __cplusplus
extern "C" {
#endif

#include "twist3.wips.h"
#include <string.h>

#define PY_SSIZE_T_CLEAN
#include "twist3_pyapi.wips.h"

#define WIPS_INTERNAL
#include "wips_detail.h"

// init

static void _wips_twist3_void_destructor(void *ptr) {
    wips_twist3_destroy((wips_twist3_t *)ptr);
}

static PyObject *wips_twist3_PyObject_new(PyTypeObject* type, PyObject *Py_UNUSED(args), PyObject *Py_UNUSED(kwds)) {
    
    wips_twist3_PyObject *obj;

    obj = (wips_twist3_PyObject *)(type->tp_alloc(type,0));
    if (obj) {
        obj->base.wips_type = &wips_twist3_PyType;
        obj->base.handler = NULL;
        obj->c_obj = NULL;
        return (PyObject *)obj;
    } else {
        PyErr_SetString(PyExc_RuntimeError, "Failed to initialize twist3");
        return NULL;
    }
}

static int wips_twist3_PyObject_init(PyObject *self, PyObject *Py_UNUSED(args), PyObject *Py_UNUSED(kwds)) {

    wips_twist3_PyObject *obj = (wips_twist3_PyObject *)self;

    wips_twist3_t *c_obj = wips_twist3_create();
    if (!c_obj) {
        PyErr_NoMemory();
        return -1;
    }
    wips_PyHandler *handler = wips_PyHandler_create((void *)c_obj,_wips_twist3_void_destructor);
    if (!handler) {
        PyErr_NoMemory();
        return -1;
    }

    obj->c_obj = c_obj;
    obj->base.handler = handler;

    return 0;
}

static void wips_twist3_PyObject_dealloc(PyObject *self) {

    wips_twist3_PyObject *obj = (wips_twist3_PyObject *)self;

    if (obj->base.handler) {
        wips_PyHandler_decref(obj->base.handler);
        obj->base.handler = NULL;
        obj->base.wips_type = NULL;
        obj->c_obj = NULL;
    }

    Py_TYPE(self)->tp_free(self);
}

// getsetters
static PyObject *wips_twist3_PyObject_get_dx(PyObject *self, void *Py_UNUSED(closure)) {
    wips_twist3_PyObject *obj = (wips_twist3_PyObject *)self;
    if (!obj->c_obj) {
        PyErr_SetString(PyExc_AttributeError,"Struct is not initialized");
        return NULL;
    }

    wips_PyType *fieldtype = &wips_fp64_PyType;
    void *c_field = (void *)(&(obj->c_obj->dx));
    PyObject *py_field = fieldtype->wrapper(c_field,obj->base.handler);
    if (!py_field) {
        // Failed to wrap value, propagate error
        return NULL;
    }
    return py_field;
}
static int wips_twist3_PyObject_set_dx(PyObject *self, PyObject *value, void *Py_UNUSED(closure)) {
    wips_twist3_PyObject *obj = (wips_twist3_PyObject *)self;
    if (!obj->c_obj) {
        PyErr_SetString(PyExc_AttributeError,"Struct is not initialized");
        return -1;
    }

    // value is not None
    // verify value is of the correct type
    wips_PyType *valtype = &wips_fp64_PyType;
    if (Py_TYPE(value) != valtype->python_type) {
        PyErr_SetString(PyExc_TypeError,"Argument type does not match field type");
        return -1;
    }
    // assign value
    wips_fp64_t *c_src = (wips_fp64_t *)(valtype->unwrapper(value));
    if (!c_src) {
        // Failed to unwrap value, propagate error
        return -1;
    }
    wips_fp64_t *c_dest = &(obj->c_obj->dx);
    wips_status_t copy_status = wips_fp64_copy(
        c_dest,
        c_src
    );
    if (copy_status != WIPS_STATUS_OK) {
        PyErr_SetString(PyExc_RuntimeError,"Failed to copy value");
        return -1;
    }
    return 0;
}
static PyObject *wips_twist3_PyObject_get_dy(PyObject *self, void *Py_UNUSED(closure)) {
    wips_twist3_PyObject *obj = (wips_twist3_PyObject *)self;
    if (!obj->c_obj) {
        PyErr_SetString(PyExc_AttributeError,"Struct is not initialized");
        return NULL;
    }

    wips_PyType *fieldtype = &wips_fp64_PyType;
    void *c_field = (void *)(&(obj->c_obj->dy));
    PyObject *py_field = fieldtype->wrapper(c_field,obj->base.handler);
    if (!py_field) {
        // Failed to wrap value, propagate error
        return NULL;
    }
    return py_field;
}
static int wips_twist3_PyObject_set_dy(PyObject *self, PyObject *value, void *Py_UNUSED(closure)) {
    wips_twist3_PyObject *obj = (wips_twist3_PyObject *)self;
    if (!obj->c_obj) {
        PyErr_SetString(PyExc_AttributeError,"Struct is not initialized");
        return -1;
    }

    // value is not None
    // verify value is of the correct type
    wips_PyType *valtype = &wips_fp64_PyType;
    if (Py_TYPE(value) != valtype->python_type) {
        PyErr_SetString(PyExc_TypeError,"Argument type does not match field type");
        return -1;
    }
    // assign value
    wips_fp64_t *c_src = (wips_fp64_t *)(valtype->unwrapper(value));
    if (!c_src) {
        // Failed to unwrap value, propagate error
        return -1;
    }
    wips_fp64_t *c_dest = &(obj->c_obj->dy);
    wips_status_t copy_status = wips_fp64_copy(
        c_dest,
        c_src
    );
    if (copy_status != WIPS_STATUS_OK) {
        PyErr_SetString(PyExc_RuntimeError,"Failed to copy value");
        return -1;
    }
    return 0;
}
static PyObject *wips_twist3_PyObject_get_dz(PyObject *self, void *Py_UNUSED(closure)) {
    wips_twist3_PyObject *obj = (wips_twist3_PyObject *)self;
    if (!obj->c_obj) {
        PyErr_SetString(PyExc_AttributeError,"Struct is not initialized");
        return NULL;
    }

    wips_PyType *fieldtype = &wips_fp64_PyType;
    void *c_field = (void *)(&(obj->c_obj->dz));
    PyObject *py_field = fieldtype->wrapper(c_field,obj->base.handler);
    if (!py_field) {
        // Failed to wrap value, propagate error
        return NULL;
    }
    return py_field;
}
static int wips_twist3_PyObject_set_dz(PyObject *self, PyObject *value, void *Py_UNUSED(closure)) {
    wips_twist3_PyObject *obj = (wips_twist3_PyObject *)self;
    if (!obj->c_obj) {
        PyErr_SetString(PyExc_AttributeError,"Struct is not initialized");
        return -1;
    }

    // value is not None
    // verify value is of the correct type
    wips_PyType *valtype = &wips_fp64_PyType;
    if (Py_TYPE(value) != valtype->python_type) {
        PyErr_SetString(PyExc_TypeError,"Argument type does not match field type");
        return -1;
    }
    // assign value
    wips_fp64_t *c_src = (wips_fp64_t *)(valtype->unwrapper(value));
    if (!c_src) {
        // Failed to unwrap value, propagate error
        return -1;
    }
    wips_fp64_t *c_dest = &(obj->c_obj->dz);
    wips_status_t copy_status = wips_fp64_copy(
        c_dest,
        c_src
    );
    if (copy_status != WIPS_STATUS_OK) {
        PyErr_SetString(PyExc_RuntimeError,"Failed to copy value");
        return -1;
    }
    return 0;
}
static PyObject *wips_twist3_PyObject_get_rx(PyObject *self, void *Py_UNUSED(closure)) {
    wips_twist3_PyObject *obj = (wips_twist3_PyObject *)self;
    if (!obj->c_obj) {
        PyErr_SetString(PyExc_AttributeError,"Struct is not initialized");
        return NULL;
    }

    wips_PyType *fieldtype = &wips_fp64_PyType;
    void *c_field = (void *)(&(obj->c_obj->rx));
    PyObject *py_field = fieldtype->wrapper(c_field,obj->base.handler);
    if (!py_field) {
        // Failed to wrap value, propagate error
        return NULL;
    }
    return py_field;
}
static int wips_twist3_PyObject_set_rx(PyObject *self, PyObject *value, void *Py_UNUSED(closure)) {
    wips_twist3_PyObject *obj = (wips_twist3_PyObject *)self;
    if (!obj->c_obj) {
        PyErr_SetString(PyExc_AttributeError,"Struct is not initialized");
        return -1;
    }

    // value is not None
    // verify value is of the correct type
    wips_PyType *valtype = &wips_fp64_PyType;
    if (Py_TYPE(value) != valtype->python_type) {
        PyErr_SetString(PyExc_TypeError,"Argument type does not match field type");
        return -1;
    }
    // assign value
    wips_fp64_t *c_src = (wips_fp64_t *)(valtype->unwrapper(value));
    if (!c_src) {
        // Failed to unwrap value, propagate error
        return -1;
    }
    wips_fp64_t *c_dest = &(obj->c_obj->rx);
    wips_status_t copy_status = wips_fp64_copy(
        c_dest,
        c_src
    );
    if (copy_status != WIPS_STATUS_OK) {
        PyErr_SetString(PyExc_RuntimeError,"Failed to copy value");
        return -1;
    }
    return 0;
}
static PyObject *wips_twist3_PyObject_get_ry(PyObject *self, void *Py_UNUSED(closure)) {
    wips_twist3_PyObject *obj = (wips_twist3_PyObject *)self;
    if (!obj->c_obj) {
        PyErr_SetString(PyExc_AttributeError,"Struct is not initialized");
        return NULL;
    }

    wips_PyType *fieldtype = &wips_fp64_PyType;
    void *c_field = (void *)(&(obj->c_obj->ry));
    PyObject *py_field = fieldtype->wrapper(c_field,obj->base.handler);
    if (!py_field) {
        // Failed to wrap value, propagate error
        return NULL;
    }
    return py_field;
}
static int wips_twist3_PyObject_set_ry(PyObject *self, PyObject *value, void *Py_UNUSED(closure)) {
    wips_twist3_PyObject *obj = (wips_twist3_PyObject *)self;
    if (!obj->c_obj) {
        PyErr_SetString(PyExc_AttributeError,"Struct is not initialized");
        return -1;
    }

    // value is not None
    // verify value is of the correct type
    wips_PyType *valtype = &wips_fp64_PyType;
    if (Py_TYPE(value) != valtype->python_type) {
        PyErr_SetString(PyExc_TypeError,"Argument type does not match field type");
        return -1;
    }
    // assign value
    wips_fp64_t *c_src = (wips_fp64_t *)(valtype->unwrapper(value));
    if (!c_src) {
        // Failed to unwrap value, propagate error
        return -1;
    }
    wips_fp64_t *c_dest = &(obj->c_obj->ry);
    wips_status_t copy_status = wips_fp64_copy(
        c_dest,
        c_src
    );
    if (copy_status != WIPS_STATUS_OK) {
        PyErr_SetString(PyExc_RuntimeError,"Failed to copy value");
        return -1;
    }
    return 0;
}
static PyObject *wips_twist3_PyObject_get_rz(PyObject *self, void *Py_UNUSED(closure)) {
    wips_twist3_PyObject *obj = (wips_twist3_PyObject *)self;
    if (!obj->c_obj) {
        PyErr_SetString(PyExc_AttributeError,"Struct is not initialized");
        return NULL;
    }

    wips_PyType *fieldtype = &wips_fp64_PyType;
    void *c_field = (void *)(&(obj->c_obj->rz));
    PyObject *py_field = fieldtype->wrapper(c_field,obj->base.handler);
    if (!py_field) {
        // Failed to wrap value, propagate error
        return NULL;
    }
    return py_field;
}
static int wips_twist3_PyObject_set_rz(PyObject *self, PyObject *value, void *Py_UNUSED(closure)) {
    wips_twist3_PyObject *obj = (wips_twist3_PyObject *)self;
    if (!obj->c_obj) {
        PyErr_SetString(PyExc_AttributeError,"Struct is not initialized");
        return -1;
    }

    // value is not None
    // verify value is of the correct type
    wips_PyType *valtype = &wips_fp64_PyType;
    if (Py_TYPE(value) != valtype->python_type) {
        PyErr_SetString(PyExc_TypeError,"Argument type does not match field type");
        return -1;
    }
    // assign value
    wips_fp64_t *c_src = (wips_fp64_t *)(valtype->unwrapper(value));
    if (!c_src) {
        // Failed to unwrap value, propagate error
        return -1;
    }
    wips_fp64_t *c_dest = &(obj->c_obj->rz);
    wips_status_t copy_status = wips_fp64_copy(
        c_dest,
        c_src
    );
    if (copy_status != WIPS_STATUS_OK) {
        PyErr_SetString(PyExc_RuntimeError,"Failed to copy value");
        return -1;
    }
    return 0;
}

static PyGetSetDef wips_twist3_PyObject_getsetters[] = {
    {
        "dx",
        (getter)wips_twist3_PyObject_get_dx,
        (setter)wips_twist3_PyObject_set_dx,
        "fp64",
        NULL
    },
    {
        "dy",
        (getter)wips_twist3_PyObject_get_dy,
        (setter)wips_twist3_PyObject_set_dy,
        "fp64",
        NULL
    },
    {
        "dz",
        (getter)wips_twist3_PyObject_get_dz,
        (setter)wips_twist3_PyObject_set_dz,
        "fp64",
        NULL
    },
    {
        "rx",
        (getter)wips_twist3_PyObject_get_rx,
        (setter)wips_twist3_PyObject_set_rx,
        "fp64",
        NULL
    },
    {
        "ry",
        (getter)wips_twist3_PyObject_get_ry,
        (setter)wips_twist3_PyObject_set_ry,
        "fp64",
        NULL
    },
    {
        "rz",
        (getter)wips_twist3_PyObject_get_rz,
        (setter)wips_twist3_PyObject_set_rz,
        "fp64",
        NULL
    },
    {NULL}
};

// wips_PyType

static void *wips_twist3_void_create() {
    return (void *)wips_twist3_create();
}

static PyObject *wips_twist3_wrap(void *c_obj, wips_PyHandler *handler) {
    wips_twist3_PyObject *obj = 
        (wips_twist3_PyObject *)wips_twist3_PyObject_new(
            &wips_twist3_PyTypeObject, NULL, NULL
        );
    
    // Failed to initialize object, propagate error
    if (!obj) return NULL;

    obj->base.handler = handler;
    obj->c_obj = (wips_twist3_t *)c_obj;
    wips_PyHandler_incref(handler);

    return (PyObject *)obj;
}

static void *wips_twist3_unwrap(PyObject *py_obj) {
    wips_twist3_PyObject *obj = (wips_twist3_PyObject *)(py_obj);
    if (!obj->c_obj) {
        PyErr_SetString(PyExc_AttributeError,"Struct is not initialized");
        return NULL;
    }

    return (void *)(obj->c_obj);
}

static wips_status_t wips_twist3_void_copier(void *dest, const void *src) {
    return wips_twist3_copy(
        (wips_twist3_t *)dest,
        (const wips_twist3_t *)src
    );
}

static PyObject *wips_twist3_extractor(void *obj) {
    PyObject *dict = PyDict_New();
    // Failed to create dict, propagate error
    if (!dict) return NULL;

    wips_twist3_t *c_obj = (wips_twist3_t *)obj;
    {
        wips_PyType *valtype = &wips_fp64_PyType;
        void *c_value = (void *)(&(c_obj->dx));
        PyObject *value = valtype->extractor(c_value);
        if (!value) {
            // failed to extract, give up
            Py_DECREF(dict);
            return NULL;
        }
        if (PyDict_SetItemString(dict, "dx", value) != 0) {
            // Failed to assign value, give up and propagate error
            Py_DECREF(dict);
            Py_DECREF(value);
            return NULL;
        }
        // Prevent memory leaks, dict assignment does not steal reference
        Py_DECREF(value);
    }
    {
        wips_PyType *valtype = &wips_fp64_PyType;
        void *c_value = (void *)(&(c_obj->dy));
        PyObject *value = valtype->extractor(c_value);
        if (!value) {
            // failed to extract, give up
            Py_DECREF(dict);
            return NULL;
        }
        if (PyDict_SetItemString(dict, "dy", value) != 0) {
            // Failed to assign value, give up and propagate error
            Py_DECREF(dict);
            Py_DECREF(value);
            return NULL;
        }
        // Prevent memory leaks, dict assignment does not steal reference
        Py_DECREF(value);
    }
    {
        wips_PyType *valtype = &wips_fp64_PyType;
        void *c_value = (void *)(&(c_obj->dz));
        PyObject *value = valtype->extractor(c_value);
        if (!value) {
            // failed to extract, give up
            Py_DECREF(dict);
            return NULL;
        }
        if (PyDict_SetItemString(dict, "dz", value) != 0) {
            // Failed to assign value, give up and propagate error
            Py_DECREF(dict);
            Py_DECREF(value);
            return NULL;
        }
        // Prevent memory leaks, dict assignment does not steal reference
        Py_DECREF(value);
    }
    {
        wips_PyType *valtype = &wips_fp64_PyType;
        void *c_value = (void *)(&(c_obj->rx));
        PyObject *value = valtype->extractor(c_value);
        if (!value) {
            // failed to extract, give up
            Py_DECREF(dict);
            return NULL;
        }
        if (PyDict_SetItemString(dict, "rx", value) != 0) {
            // Failed to assign value, give up and propagate error
            Py_DECREF(dict);
            Py_DECREF(value);
            return NULL;
        }
        // Prevent memory leaks, dict assignment does not steal reference
        Py_DECREF(value);
    }
    {
        wips_PyType *valtype = &wips_fp64_PyType;
        void *c_value = (void *)(&(c_obj->ry));
        PyObject *value = valtype->extractor(c_value);
        if (!value) {
            // failed to extract, give up
            Py_DECREF(dict);
            return NULL;
        }
        if (PyDict_SetItemString(dict, "ry", value) != 0) {
            // Failed to assign value, give up and propagate error
            Py_DECREF(dict);
            Py_DECREF(value);
            return NULL;
        }
        // Prevent memory leaks, dict assignment does not steal reference
        Py_DECREF(value);
    }
    {
        wips_PyType *valtype = &wips_fp64_PyType;
        void *c_value = (void *)(&(c_obj->rz));
        PyObject *value = valtype->extractor(c_value);
        if (!value) {
            // failed to extract, give up
            Py_DECREF(dict);
            return NULL;
        }
        if (PyDict_SetItemString(dict, "rz", value) != 0) {
            // Failed to assign value, give up and propagate error
            Py_DECREF(dict);
            Py_DECREF(value);
            return NULL;
        }
        // Prevent memory leaks, dict assignment does not steal reference
        Py_DECREF(value);
    }

    return dict;
}

wips_PyType wips_twist3_PyType = {
    .type_id = WIPS_struct,
    .size = GET_SIZE(twist3),
    .python_type = &wips_twist3_PyTypeObject,
    .vlamethods = &wips_twist3_vlamethods,
    .creator = wips_twist3_void_create,
    .wrapper = wips_twist3_wrap,
    .unwrapper = wips_twist3_unwrap,
    .destructor = _wips_twist3_void_destructor,
    .copier = wips_twist3_void_copier,
    .extractor = wips_twist3_extractor
};

// Methods

static PyObject *wips_twist3_PyObject_copy(PyObject *self, PyObject *Py_UNUSED(args)) {
    wips_twist3_PyObject *obj = (wips_twist3_PyObject *)self;
    if (!obj->c_obj) {
        PyErr_SetString(PyExc_AttributeError,"Struct is not initialized");
        return NULL;
    }

    wips_twist3_t *copy = wips_twist3_create();
    if (!copy) {
        PyErr_NoMemory();
        return NULL;
    }

    wips_status_t copy_status = wips_twist3_copy(copy,obj->c_obj);
    if (copy_status != WIPS_STATUS_OK) {
        PyErr_SetString(PyExc_RuntimeError, "Failed to copy object");
        wips_twist3_destroy(copy);
        return NULL;
    }

    wips_PyHandler *handler = wips_PyHandler_create((void *)copy,_wips_twist3_void_destructor);

    if (!handler) {
        PyErr_SetString(PyExc_RuntimeError,"Failed to create handler");
        wips_twist3_destroy(copy);
        return NULL;
    }

    PyObject *pyobj = wips_twist3_wrap((void *)copy,handler);

    if (!pyobj) {
        wips_PyHandler_decref(handler); // destroys handler and resource
        return NULL;
    }

    return pyobj;
}

static PyObject *wips_twist3_PyObject_encode(PyObject *Py_UNUSED(self), PyObject *args) {
    PyObject *py_struct;

    if (!PyArg_ParseTuple(args, "O", &py_struct)) {
        return NULL;
    }

    if (Py_TYPE(py_struct) != &wips_twist3_PyTypeObject) {
        PyErr_SetString(PyExc_TypeError, "input struct must be of type twist3");
        return NULL;
    }

    wips_twist3_t *c_obj = (wips_twist3_t *)((&wips_twist3_PyType)->unwrapper(py_struct));
    if (!c_obj) return NULL;

    wips_blob_t *blob = wips_blob_create(GET_SIZE(twist3));

    wips_result_t encode_status = wips_encode_twist3(blob, c_obj);
    if (encode_status.status_code != WIPS_STATUS_OK) {
        PyErr_SetString(PyExc_RuntimeError, "Failed to encode twist3");
        wips_blob_destroy(blob);
        return NULL;
    }

    PyObject *pyblob = (PyObject *)wips_blob_PyObject_create(blob);
    if (!pyblob) {
        wips_blob_destroy(blob);
        return NULL;
    }

    return pyblob;
}

static PyObject *wips_twist3_PyObject_decode(PyObject *Py_UNUSED(self), PyObject *args) {
    PyObject *pyblob;

    if (!PyArg_ParseTuple(args, "O", &pyblob)) {
        return NULL;
    }

    if (Py_TYPE(pyblob) != &wips_blob_PyTypeObject) {
        PyErr_SetString(PyExc_TypeError, "input struct must be a wips blob");
        return NULL;
    }

    wips_twist3_t *c_obj = wips_twist3_create();
    wips_blob_t *c_blob = ((wips_blob_PyObject *)(pyblob))->c_obj;

    if (!c_blob) {
        PyErr_SetString(PyExc_RuntimeError, "Blob is NULL");
        wips_twist3_destroy(c_obj);
        return NULL;
    }

    wips_result_t decode_status = wips_decode_twist3(c_obj,c_blob);

    if (decode_status.status_code != WIPS_STATUS_OK) {
        PyErr_SetString(PyExc_RuntimeError, "Failed to decode twist3");
        wips_twist3_destroy(c_obj);
        return NULL;
    }

    wips_PyHandler *handler = wips_PyHandler_create((void *)c_obj, _wips_twist3_void_destructor);
    if (!handler) {
        PyErr_SetString(PyExc_RuntimeError,"Failed to create handler");
        wips_twist3_destroy(c_obj);
        return NULL;
    }

    PyObject *pyobj = wips_twist3_wrap((void *)c_obj, handler);
    if (!pyobj) {
        wips_PyHandler_decref(handler); // destroys handler and resource
        return NULL;
    }
    
    return pyobj;
}

static PyObject *wips_twist3_PyObject_extract(PyObject *self, PyObject *Py_UNUSED(args)) {
    wips_twist3_PyObject *obj = (wips_twist3_PyObject *)self;
    if (!obj->c_obj) {
        PyErr_SetString(PyExc_AttributeError,"Struct is not initialized");
        return NULL;
    }

    return (&wips_twist3_PyType)->extractor((void *)(obj->c_obj));
}

static PyMethodDef wips_twist3_PyObject_methods[] = {
    {
        "encode",
        wips_twist3_PyObject_encode,
        METH_VARARGS | METH_STATIC,
        "Encodes a struct"
    },
    {
        "decode",
        wips_twist3_PyObject_decode,
        METH_VARARGS | METH_STATIC,
        "Decodes a blob"
    },
    {
        "copy",
        wips_twist3_PyObject_copy,
        METH_NOARGS,
        "Creates a deep copy"
    },
    {
        "extract",
        wips_twist3_PyObject_extract,
        METH_NOARGS,
        "Extracts struct to a python dict"
    },
    {NULL, NULL, 0, NULL}
};

PyTypeObject wips_twist3_PyTypeObject = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name = "wips.twist3",
    .tp_basicsize = GET_SIZE(twist3),
    .tp_flags = Py_TPFLAGS_DEFAULT,
    .tp_base = &wips_struct_PyTypeObject,
    .tp_new = wips_twist3_PyObject_new,
    .tp_init = wips_twist3_PyObject_init,
    .tp_dealloc = wips_twist3_PyObject_dealloc,
    .tp_methods = wips_twist3_PyObject_methods,
    .tp_getset = wips_twist3_PyObject_getsetters
};

static void wips_twist3_static_method_init(void) {
    
}

int wips_twist3_PyTypeObject_init(PyObject *m) {
    
    if (PyType_Ready(&wips_twist3_PyTypeObject) < 0) {
        return -1;
    }

    Py_INCREF(&wips_twist3_PyTypeObject);
    if (PyModule_AddObject(m, "twist3", (PyObject *)&wips_twist3_PyTypeObject) < 0) {
        Py_DECREF(&wips_twist3_PyTypeObject);
        return -1;
    }

    return 0;
}

#ifdef __cplusplus
}
#endif

#endif // WIPS_OPTION_BUILD_PYTHON