/*
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (c) 2025 Jesse Kane
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from this
 * software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS”
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

// This file was automatically generated by WIPS. Do not attempt to modify manually

#ifdef __cplusplus
extern "C" {
#endif

#include "wips_pyapi.h"

// NOTE: This implementation is not thread-safe. Safe under the GIL
struct wips_handler {
    void* resource;
    size_t refcount;
    void (*destructor)(void*)
};

wips_handler_t* wips_handler_create(void* resource,void (*destructor)(void*)) {
    wips_handler_t* handler = (wips_handler_t*)malloc(sizeof(wips_handler_t));
    if (!handler) return NULL;
    handler->resource = resource;
    handler->destructor = destructor;
    handler->refcount = 1;
    return handler;
}

wips_handler_t* wips_handler_incref(wips_handler_t* handler) {
    if (!handler) return NULL;
    handler->refcount++;
    return handler;
}

wips_handler_t* wips_handler_decref(wips_handler_t* handler) {
    if (!handler) return NULL;
    handler->refcount--;
    if (!(handler->refcount)) {
        if (!handler->destructor) {
            free(handler->resource);
        } else {
            handler->destructor(handler->resource);
        }
        free(handler);
        return NULL;
    }
    return handler;
}

// The pointer returned by this function is owned by the handler and should NOT be freed manually
void* wips_handler_get(wips_handler_t* handler) {
    if (!handler) return NULL;
    return handler->resource;
}

static wips_status_t pyssize_to_size(Py_ssize_t val) {
    if (val < 0) {
        fprintf(stderr, "Error: negative Py_ssize_t value cannot be converted to size_t\n");
        return wips_make_status(0,WIPS_STATUS_OVERFLOW);
    }
    return wips_make_status((size_t)val,WIPS_STATUS_OK);
}


static void wips_blob_PyObject_dealloc(PyObject* self) {

    wips_blob_PyObject* obj = (wips_blob_PyObject*)self;

    if (obj->c_obj) {
        wips_bin_destroy(obj->c_obj);
        obj->c_obj = NULL;
    }

    Py_TYPE(self)->tp_free(self);
}


static PyObject* wips_blob_PyObject_new(PyTypeObject* type, PyObject* args, PyObject* kwds) {

    wips_blob_PyObject* self;

    self = (wips_blob_PyObject*)(type->tp_alloc(type,0));
    if (self) {
        self->c_obj = NULL;
    }

    return (PyObject*)self;
}

static int wips_blob_PyObject_init(PyObject* self, PyObject* args, PyObject* kwds) {

    const char* buffer;
    Py_ssize_t py_size;
    
    if (!PyArg_ParseTuple(args,"y#",&buffer,&py_size)) {
        return -1;
    }

    wips_status_t size_result = pyssize_to_size(py_size);
    if (size_result.status_code == WIPS_STATUS_OVERFLOW){
        PyErr_SetString(PyExc_ValueError, "Negative buffer length");
        return -1;
    }

    size_t size = size_result.bytes_processed;

    wips_blob_PyObject *obj = (wips_blob_PyObject*)self;

    unsigned char* base = (unsigned char*)malloc(size);
    if (!base) {
        PyErr_NoMemory();
        return -1;
    }

    memcpy(base,buffer,size);
    wips_blob_t* c_blob = wips_blob_wrap(base,size);

    if (!c_blob) {
        free(base);
        PyErr_NoMemory();
        return -1;
    }

    obj->c_obj = c_blob;
    return 0;
}

static int wips_blob_PyObject_getbuffer(PyObject* self, Py_buffer* view, int flags) {
    wips_blob_PyObject* obj = (wips_blob_PyObject*)self;

    if (!obj->c_obj) {
        PyErr_SetString(PyExc_BufferError, "Underlying buffer is NULL");
        return -1;
    }

    view->buf = (void*)(obj->c_obj->base); 
    view->obj = self;
    view->readonly = 1;

    // Expose entire allocated buffer, since WIPS doesn't define size semantics beyond that
    view->len = obj->c_obj->allocated;
    Py_INCREF(self);

    view->itemsize = 1;
    view->ndim = 1;
    view->format = "B";
    view->shape = NULL; 
    view->strides = NULL;
    view->suboffsets = NULL;
    view->internal = NULL;

    return 0;
}

static PyObject* wips_blob_PyObject_get_offset(PyObject* self, void* closure) {
    wips_blob_PyObject* obj = (wips_blob_PyObject*)self;
    return PyLong_FromSize_t(obj->c_obj->offset);
}

static int wips_blob_PyObject_set_offset(PyObject* self, PyObject* value, void* closure) {
    wips_blob_PyObject* obj = (wips_blob_PyObject*)self;

    if (!PyLong_Check(value)) {
        PyErr_SetString(PyExc_TypeError, "The 'value' attribute must be an int");
        return -1;
    }

    size_t val = PyLong_AsSize_t(value);
    if (val == -1 && PyErr_Occurred()) {
        return -1;  // error converting
    }

    obj->c_obj->offset = val;
    return 0;
}

static PyBufferProcs wips_blob_PyObject_as_buffer = {
    .bf_getbuffer = wips_blob_PyObject_getbuffer,
    .bf_releasebuffer = NULL
};

static PyGetSetDef wips_blob_PyObject_getsetters[] = {
    {"offset",(getter)wips_blob_PyObject_get_offset,(setter)wips_blob_PyObject_set_offset,NULL,NULL},
    {NULL}
};

static PyTypeObject wips_blob_PyTypeObject = {
    PyVarObject_HEAD_INIT(NULL,0)
    .tp_name = "wips.blob",
    .tp_basicsize = sizeof(wips_blob_PyObject),
    .tp_dealloc = wips_blob_PyObject_dealloc,
    .tp_as_buffer = &wips_blob_PyObject_as_buffer,
    .tp_new = wips_blob_PyObject_new,
    .tp_init = (initproc)wips_blob_PyObject_init,
    .tp_flags = Py_TPFLAGS_DEFAULT,
    .tp_getset = wips_blob_PyObject_getsetters
};

#ifdef __cplusplus
}
#endif
