/*
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (c) 2025 Jesse Kane
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from this
 * software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS”
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

// This file was automatically generated by WIPS. Do not attempt to modify manually

#ifdef __cplusplus
extern "C" {
#endif

#include "wips_pyapi.h"

// NOTE: This implementation is not thread-safe. Safe under the GIL
struct wips_handler {
    void* resource;
    size_t refcount;
    void (*destructor)(void*)
};

wips_handler_t* wips_handler_create(void* resource,void (*destructor)(void*)) {
    wips_handler_t* handler = (wips_handler_t*)malloc(sizeof(wips_handler_t));
    if (!handler) return NULL;
    handler->resource = resource;
    handler->destructor = destructor;
    handler->refcount = 1;
    return handler;
}

wips_handler_t* wips_handler_incref(wips_handler_t* handler) {
    if (!handler) return NULL;
    handler->refcount++;
    return handler;
}

wips_handler_t* wips_handler_decref(wips_handler_t* handler) {
    if (!handler) return NULL;
    handler->refcount--;
    if (!(handler->refcount)) {
        if (!handler->destructor) {
            free(handler->resource);
        } else {
            handler->destructor(handler->resource);
        }
        free(handler);
        return NULL;
    }
    return handler;
}

// The pointer returned by this function is owned by the handler and should NOT be freed manually
void* wips_handler_get(wips_handler_t* handler) {
    if (!handler) return NULL;
    return handler->resource;
}

static inline unsigned char pyssize_to_size(size_t* out,Py_ssize_t val) {
    if (val < 0)
        return WIPS_STATUS_UNDERFLOW;
    (*out) = (size_t)val;
    return WIPS_STATUS_OK;
}

static inline unsigned char size_to_pyssize(Py_ssize_t* out,size_t val) {
    if (val > (size_t)PY_SSIZE_T_MAX)
        return WIPS_STATUS_OVERFLOW;
    (*out) = (Py_ssize_t)val;
    return WIPS_STATUS_OK;
}


// blob methods
static void wips_PyBlob_dealloc(PyObject* self) {

    wips_PyBlob* obj = (wips_PyBlob*)self;

    if (obj->c_obj) {
        wips_bin_destroy(obj->c_obj);
        obj->c_obj = NULL;
    }

    Py_TYPE(self)->tp_free(self);
}


static PyObject* wips_PyBlob_new(PyTypeObject* type, PyObject* args, PyObject* kwds) {

    wips_PyBlob* self;

    self = (wips_PyBlob*)(type->tp_alloc(type,0));
    if (self) {
        self->c_obj = NULL;
    }

    return (PyObject*)self;
}

static int wips_PyBlob_init(PyObject* self, PyObject* args, PyObject* kwds) {

    const char* buffer;
    Py_ssize_t py_size;
    size_t size;
    
    if (!PyArg_ParseTuple(args,"y#",&buffer,&py_size)) {
        return -1;
    }

    unsigned char size_status = pyssize_to_size(&size,py_size);
    if (size_status == WIPS_STATUS_UNDERFLOW){
        PyErr_SetString(PyExc_ValueError, "Negative buffer length");
        return -1;
    }

    wips_PyBlob *obj = (wips_PyBlob*)self;

    unsigned char* base = (unsigned char*)malloc(size);
    if (!base) {
        PyErr_NoMemory();
        return -1;
    }

    memcpy(base,buffer,size);
    wips_blob_t* c_blob = wips_blob_wrap(base,size);

    if (!c_blob) {
        free(base);
        PyErr_NoMemory();
        return -1;
    }

    obj->c_obj = c_blob;
    return 0;
}

static int wips_PyBlob_getbuffer(PyObject* self, Py_buffer* view, int flags) {
    wips_PyBlob* obj = (wips_PyBlob*)self;

    if (!obj->c_obj) {
        PyErr_SetString(PyExc_BufferError, "Underlying buffer is NULL");
        return -1;
    }

    view->buf = (void*)(obj->c_obj->base); 
    view->obj = self;
    view->readonly = 1;

    // Expose entire allocated buffer, since WIPS doesn't define size semantics beyond that
    view->len = obj->c_obj->allocated;
    Py_INCREF(self);

    view->itemsize = 1;
    view->ndim = 1;
    view->format = "B";
    view->shape = NULL; 
    view->strides = NULL;
    view->suboffsets = NULL;
    view->internal = NULL;

    return 0;
}

static PyObject* wips_PyBlob_get_offset(PyObject* self, void* closure) {
    wips_PyBlob* obj = (wips_PyBlob*)self;
    return PyLong_FromSize_t(obj->c_obj->offset);
}

static int wips_PyBlob_set_offset(PyObject* self, PyObject* value, void* closure) {
    wips_PyBlob* obj = (wips_PyBlob*)self;

    if (!PyLong_Check(value)) {
        PyErr_SetString(PyExc_TypeError, "The 'value' attribute must be an int");
        return -1;
    }

    size_t val = PyLong_AsSize_t(value);
    if (val == -1 && PyErr_Occurred()) {
        return -1;  // error converting
    }

    obj->c_obj->offset = val;
    return 0;
}

static PyBufferProcs wips_PyBlob_as_buffer = {
    .bf_getbuffer = wips_PyBlob_getbuffer,
    .bf_releasebuffer = NULL
};

static PyGetSetDef wips_PyBlob_getsetters[] = {
    {"offset",(getter)wips_PyBlob_get_offset,(setter)wips_PyBlob_set_offset,NULL,NULL},
    {NULL}
};

// vla methods
wips_vla_PyObject_dealloc(PyObject* self) {

    wips_vla_PyObject* obj = (wips_vla_PyObject*)self;

    if (obj->base.handler) {
        wips_handler_decref(obj->base.handler);
        free(obj->buffer_pt);
        obj->buffer_pt = NULL;
        obj->vlasize = NULL;
        obj->base.handler = NULL;
        obj->base.wips_type = NULL;
    }

    Py_TYPE(self)->tp_free(self);
}

PyObject* wips_vla_PyObject_create(unsigned char* buffer, wips_u32_t* vlasize, wips_handler_t* handler, wips_pytype_t* wips_type) {
    PyTypeObject* type = &wips_vla_PyTypeObject;
    wips_vla_PyObject* obj = (wips_vla_PyObject*)(type->tp_alloc(type,0));
    if (!obj) return NULL;
    unsigned char** buffer_pt = (unsigned char**)malloc(sizeof(unsigned char*));
    *buffer_pt = buffer;
    obj->buffer_pt = buffer_pt;
    obj->vlasize = vlasize;
    obj->base.handler = handler;
    obj->base.wips_type = wips_type;
    return (PyObject*)obj;
}

static Py_ssize_t wips_vla_PyObject_length(PyObject* self) {
    wips_vla_PyObject* obj = (wips_vla_PyObject*)self;
    Py_ssize_t pysize;
    unsigned char size_status = size_to_pyssize(&pysize,*(obj->vlasize));
    if (!obj->vlasize) {
        PyErr_SetString(PyExc_RuntimeError, "vlasize pointer is NULL");
        return -1;
    }
    if (size_status == WIPS_STATUS_OVERFLOW){
        PyErr_SetString(PyExc_OverflowError,"vla is too large");
        return -1;
    }
    return pysize;
}

static PyObject* wips_vla_PyObject_item(PyObject* self,Py_ssize_t index) {
    wips_vla_PyObject* obj = (wips_vla_PyObject*)self;
    size_t real_index;
    unsigned char index_status = pyssize_to_size(&real_index,index);
    if (index_status == WIPS_STATUS_UNDERFLOW) // index is negative, subtract from the end of the sequence
        real_index = *(obj->vlasize) - (size_t)(-index);
    if (real_index > *(obj->vlasize)) {
        PyErr_SetString(PyExc_IndexError, "index out of range");
        return NULL;
    }
    unsigned char* c_obj = *(obj->buffer_pt) + (real_index * (obj->base.wips_type->size));
    return obj->base.wips_type->wrapper(c_obj,obj->base.handler);
}

static PyObject* wips_vla_PyObject_ass_item(PyObject* self, Py_ssize_t index, PyObject* value) {
    wips_vla_PyObject* obj = (wips_vla_PyObject*)self;
    size_t real_index;
    unsigned char index_status = pyssize_to_size(&real_index,index);
    if (index_status == WIPS_STATUS_UNDERFLOW) // index is negative, subtract from the end of the sequence
        real_index = *(obj->vlasize) - (size_t)(-index);
    if (real_index > *(obj->vlasize)) {
        PyErr_SetString(PyExc_IndexError, "index out of range");
        return NULL;
    }
    if (value) {

    } else {
        // Value is NULL, delete
        (*buffer)
    }
}



// Type objects
PyTypeObject wips_PyBlobTypeObject = {
    PyVarObject_HEAD_INIT(NULL,0)
    .tp_name = "wips.blob",
    .tp_basicsize = sizeof(wips_PyBlob),
    .tp_dealloc = wips_PyBlob_dealloc,
    .tp_as_buffer = &wips_PyBlob_as_buffer,
    .tp_new = wips_PyBlob_new,
    .tp_init = (initproc)wips_PyBlob_init,
    .tp_flags = Py_TPFLAGS_DEFAULT,
    .tp_getset = wips_PyBlob_getsetters
};

PyTypeObject wips_PyObjectTypeObject = {
    PyVarObject_HEAD_INIT(NULL,0)
    .tp_name = "wips.PyObject",
    .tp_basicsize = sizeof(wips_PyObject),
    .tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE
};

static PyTypeObject wips_vla_PyTypeObject = {
    PyVarObject_HEAD_INIT(NULL,0)
    .tp_name = "wips.vla"
};

#ifdef __cplusplus
}
#endif
