name: Build & Local Install

on:
  workflow_dispatch:

jobs:
  build:
    name: "Wayfinder - Build"
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build & stage wayfinder
      run: ./tools/build.sh