name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Wayfinder - Build"
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache build
      uses: actions/cache@v4
      with:
        path: build
        key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
        restore-keys: |
          ${{ runner.os }}-build-
    
    - name: Update packages
      run: sudo apt-get update
          
    - name: Install OpenCV
      run: sudo apt install -y libopencv-dev
          
    - name: Configure & Build wayfinder
      run: cmake --preset ci && cmake --build --preset ci

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          build/
          !build/CMakeFiles 
    
  test:
    name: "Wayfinder - Test"
    runs-on: ubuntu-latest
    needs: build

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update packages
      run: sudo apt-get update

    - name: Install OpenCV
      run: sudo apt install -y libopencv-dev

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: build
            
    - name: Set permissions for test executables
      run: find build -name '*_tests' -exec chmod +x {} +
    
    - name: Load test environment
      run: source tools/load-test-env.sh

    - name: Test
      run: ctest --test-dir build/ci --verbose




            
