name: Build

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build-core:
        name: "Wayfinder - Build Core"
        runs-on: ubuntu-latest
        steps:

          - name: Checkout code
            uses: actions/checkout@v4

          - name: Cache build
            uses: actions/cache@v4
            with:
                path: build
                key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
                restore-keys: |
                    ${{ runner.os }}-build-

          - name: Install Ninja
            run: sudo apt update && sudo apt install -y ninja-build
        
          - name: Install OpenCV
            run: sudo apt install libopencv-dev

          - name: Configure CMake
            run: cmake -S . -B build -G Ninja
        
          - name: Build
            run: cmake --build build

          - name: Upload build artifacts
            uses: actions/upload-artifact@v4
            with:
                name: build-artifacts
                path: |
                    build/
                    !build/CMakeFiles 
    
    test-core:
        name: "Wayfinder - Test Core"
        runs-on: ubuntu-latest
        needs: build-core

        steps:

          - name: Checkout code
            uses: actions/checkout@v4

          - name: Install OpenCV
            run: sudo apt install libopencv-dev

          - name: Download build artifacts
            uses: actions/download-artifact@v4
            with:
                name: build-artifacts
                path: build
            
          - name: Set permissions for test executables
            run: find build -name '*_tests' -exec chmod +x {} +

          - name: Test
            run: ctest --test-dir build --verbose




            
